elastic/eland

CHANGELOG.rst
eland/_version.py

Preparing for a release of v7.6.0a4, will build and push to PyPI after merging.

Prepare release for v7.6.0a4

---

eland/tests/common.py
eland/tests/dataframe/test_utils_pytest.py
eland/utils.py

Parameter is useful when adding multiple pd.DataFrame's to
the same index.
Also, updated test module to pandas.testing for 1.0.x
compliance,

Adding ignore_index to pandas_to_eland

---

eland/ml/_model_serializer.py

Experimentally this makes serialized ML models from the test suite ~1% smaller. Not sure how big they can get or if this matters much but this is how clients all dump JSON.

No spaces in delimiters for serialized ML model

---

eland/operations.py
eland/tests/dataframe/test_aggs_pytest.py

The percentiles query result look like this: `{"percentiles_X": {"values": {"50.0": <value>}}}`, need the extra level of unpacking compared to all other tuple agg types so far.

Fix unpacking of median aggregation result

---

eland/ndframe.py
eland/operations.py
eland/query_compiler.py
eland/tests/dataframe/test_metrics_pytest.py

This add the functions var and std. It mirrors the same implementation of the other metric aggregations.
The changes were made in `_metric_aggs`, for two reasons:
1. To keep all logic related to the aggregating functions in the same place.
2. extended_stats are metric aggregations in Elasticsearch API.
Closes #171

Add functions var, std 

---

eland/ndframe.py
eland/operations.py
eland/query_compiler.py
eland/tests/dataframe/test_metrics_pytest.py

Includes:
- Add implementation of median
- Add docstring of std, var and, median
- Run black

Add median()  to ndframe

---

eland/operations.py
eland/tests/dataframe/test_metrics_pytest.py
eland/tests/ml/test_imported_ml_model_pytest.py

Fixing var, std and flaky tests

---

eland/operations.py
eland/tests/dataframe/test_dtypes_pytest.py

In case the content of the series if empty, the code should create the series with a the matching dtype of pandas.
Closes #165

Add default dtype for empty series

---

eland/actions.py
eland/arithmetics.py
eland/common.py
eland/dataframe.py
eland/filter.py
eland/index.py
eland/operations.py
eland/query.py
eland/query_compiler.py
eland/tasks.py
eland/utils.py
noxfile.py

This starts on #19 by adding type hints to all the base modules in `eland`. After this may be useful to look at an "automatic" type hint generator since now most types can be inferred.
Also want to wait to do query_compiler.py and operations.py until we have a query_params dataclass (#193)

Add type hints to base modules

---

.ci/run-repository.sh
docs/requirements-docs.txt
eland/common.py
eland/dataframe.py
eland/field_mappings.py
eland/ndframe.py
eland/operations.py
eland/query_compiler.py
eland/series.py
eland/tests/dataframe/test_dtypes_pytest.py
eland/tests/dataframe/test_metrics_pytest.py
eland/tests/operations/test_map_pd_aggs_to_es_aggs_pytest.py
eland/tests/series/test_dtype_pytest.py
eland/tests/series/test_metrics_pytest.py
requirements-dev.txt
requirements.txt
setup.py

This PR still needs a little work, putting it up early so @mesejo can see what I'm up to.
Basically the thought process is we're using FIeldMapping to store a lot of information but the APIs only allow access to a subset of the information per function call, instead we should focus on putting a lot of the "smarts" in the `Field` class so that it's all localized (like which aggregations can be used on a certain Field, etc)
I'd like to continue moving the return types of `FieldMapping` to be mostly just `Field`s.
This also has the plus of making it easy to fill in `NaN` whenever an aggregation isn't possible for ES in the same way that Pandas does this (like calling `.mean()` on a string type)
Still need to add a bunch of tests for this functionality.

Add Field from FieldMapping with all info on field

---

eland/filter.py
eland/tests/operators/test_operators_pytest.py

Changes how we detect whether to combine an `AndFilter`/`OrFilter` with another `bool` query.
Essentially we want the `"bool"` to appear in the `subtree["must"]` of the query being combined into.
From #203 the query that was being generated and causing an error is:
```json
{
"bool": {
"must": [
{"range": {"a": {"gt": 10}}},
{"range": {"a": {"gt": 250}}},
{"should": [{"term": {"b": "X"}}, {"term": {"b": "Y"}}]},  <--- this entry is wrong
{"term": {"b": "Z"}},
]
}
}
```
with this change now this query will be generated:
```json
{
"bool": {
"must": [
{"range": {"a": {"gt": 10}}},
{"range": {"a": {"gt": 250}}},
{"bool": {"should": [{"term": {"b": "X"}}, {"term": {"b": "Y"}}]}},
{"term": {"b": "Z"}},
]
}
}
```
Closes #203 
cc @penalva34

Fix bug when combining AndFilter/OrFilter with other bool filters

---

eland/operations.py
eland/tasks.py
eland/tests/dataframe/test_head_tail_pytest.py

This is an attempt at solving the bug with the wrong shape, instead of only passing the sort field, one could pass the index and query the `len` in the constructor. An enhancement will be to create a unique constructor in SizeTask with the logic.
Closes #152

Fix bug with empty dataframe number of rows

---

eland/_version.py
requirements-dev.txt
requirements.txt
setup.py

Now that `elasticsearch-py` has been released with `numpy` and `pandas` serialization support we no longer need to rely on alphas!

Upgrade to elasticsearch-py v7.7

---

docs/source/conf.py
docs/source/reference/api/eland.Series.isna.rst
docs/source/reference/api/eland.Series.notna.rst
docs/source/reference/series.rst
eland/filter.py
eland/series.py
eland/tests/operators/test_operators_pytest.py
eland/tests/series/test_na_pytest.py

This commits includes: 
1. The basic functionality for isna, notna functions
2. The documentation 
3. Update pandas docs external links
Closes #184

Add isna, notna functions

---

eland/dataframe.py
eland/operations.py
eland/query.py
eland/query_compiler.py
eland/series.py
eland/tasks.py
eland/tests/common.py
eland/tests/dataframe/test_drop_pytest.py
eland/tests/dataframe/test_filter_pytest.py
eland/tests/series/test_filter_pytest.py

- Adds support for `.filter()` on `DataFrame` and `Series`
- Supports `items`, `like`, and `regex` for `axis=columns` on `DataFrame.filter()`
- Supports `items` for `axis=index` on `Series.filter()
- Renames `Series.field_name` to `Series.es_field_name`
- Fixes a bug where setting `DataFrame.columns` to `[]` would still query all dataframe columns
Closes #198

Add [DataFrame, Series].filter()

---

eland/dataframe.py
eland/tests/dataframe/test_dir_pytest.py
eland/tests/test_utils_pytest.py
eland/utils.py

Closes https://github.com/elastic/eland/issues/222

Dataframe column names autocompletion

---

eland/ml/imported_ml_model.py
eland/tests/ml/test_imported_ml_model_pytest.py
requirements-dev.txt

- Adds support for submitting uncompressed ML model definitions. This helps if users want to receive errors immediately when creating a model over the compressed definition which errors out on first usage. Eland also happened to find an Elasticsearch bug by using the compressed definition so it'd be good to test both.
- Changes `ImportedMLModel.predict()` to error out if an `error` is received within `docs` without a non-2XX HTTP status code.

Error when ingest.simulate fails without non-2XX HTTP status code

---

eland/tests/conftest.py
eland/tests/dataframe/test_count_pytest.py
eland/tests/dataframe/test_drop_pytest.py
eland/tests/dataframe/test_dtypes_pytest.py
eland/tests/dataframe/test_filter_pytest.py
eland/tests/dataframe/test_get_pytest.py
eland/tests/dataframe/test_getitem_pytest.py

The object maintains an Eland object and Pandas object which are initially a DataFrame. The object then responds to all API calls by applying the call to each object and comparing the results. If the results are both Pandas objects or literals then we stop tracking otherwise the tracking continues. This lets us write shorter test cases and exercise similarities between the two APIs more easily.
If this is desirable it can no doubt be applied to more test cases.

Use SymmetricalAPIChecker for testing same behavior/results

---

eland/ml/_model_serializer.py
eland/ml/imported_ml_model.py
eland/ml/transformers/sklearn.py
eland/ml/transformers/xgboost.py
eland/tests/ml/test_imported_ml_model_pytest.py

This commit adds support for XGBoost multi-class classification model transformations.
XGBoost handles multiclass classification by having `n_classes * n_estimators` trees. 
Then, every `n_classes` tree corresponds to their respective classes
Since Elasticsearch supports multi-valued leaves, we can transform the xgboost format by choosing the
appropriate leaf value index given the tree id.
This commit also fixes a minor model transformation bug where if xgboost actually defined the feature_names instead of the default `f1,...fn` we would blow up. 
closes https://github.com/elastic/eland/issues/242

[ML] add multi:softmax|softprob XGBoost support

---

eland/ml/imported_ml_model.py
eland/ml/transformers/__init__.py
eland/ml/transformers/lightgbm.py
eland/tests/ml/test_imported_ml_model_pytest.py

Adds support for transforming LGBMClassifier models. 
We are able to support binary, multiclass, and multiclassova. These are the only valid ones for classification. 
But, still restricting to prevent a regression where lightgbm adds a new objective without us knowing.

[ML] add LGBMClassifier transform support

---

CONTRIBUTING.md
README.md
eland/ml/imported_ml_model.py
eland/ml/ml_model.py
eland/tests/ml/test_imported_ml_model_pytest.py
eland/utils.py

Closes #225 
- Added es_if_exists in ImportedMLModel and deprecated the overwrite parameter.
- Updated the tests of ImportedMLModel.
- Updated Contributing guidelines for installation instructions using Docker for helping new contributors.
- Updated info_es() to es_info() (because info_es() is deprecated)

Replace MLModel(overwrite) with es_if_exists

---

.gitattributes
eland/dataframe.py
eland/field_mappings.py
eland/ndframe.py
eland/operations.py
eland/query_compiler.py
eland/tests/dataframe/test_aggs_pytest.py
eland/tests/dataframe/test_metrics_pytest.py
eland/tests/series/test_metrics_pytest.py

Closes #254 
- Added numeric_only = True | False | None for all agg and aggs (except nunique)
- Added logic where booleans are not supported by median_absolute_deviation
- Added tests, doctests for every change made, also modified existing tests to work with these changes.
- Nox and pytest sessions are successful.

Switch agg defaults to numeric_only=None

---

eland/etl.py

PR on #238 
@sethmlarson Please check this 
- Implemented as described in the issue.
- Just in case, took reference of the following:
https://discuss.elastic.co/t/helpers-parallel-bulk-in-python-not-working/39498/2

Improve efficiency of `pandas_to_eland()` using `parallel_bulk()`

---

eland/actions.py
eland/operations.py
eland/query_compiler.py
eland/tasks.py
eland/tests/dataframe/test_filter_pytest.py
eland/utils.py

Closes #245 
- Added typehints wherever necessary w.r.t filter 
Example:
```python
>>> ed_flights = ed.DataFrame("localhost", "flights")
>>> ed_flights.filter(axis="index", items = ["1", "2", "0"])
AvgTicketPrice  Cancelled           Carrier                                          Dest  ... OriginRegion OriginWeather dayOfWeek           timestamp
1      882.982662      False  Logstash Airways                     Venice Marco Polo Airport  ...        SE-BD         Clear         0 2018-01-01 18:27:00
2      190.636904      False  Logstash Airways                     Venice Marco Polo Airport  ...        IT-34          Rain         0 2018-01-01 17:11:14
0      841.265642      False   Kibana Airlines  Sydney Kingsford Smith International Airport  ...        DE-HE         Sunny         0 …
```

dataframe.filter should preserve order of items

---

MANIFEST.in
eland/common.py
eland/etl.py
eland/ml/ml_model.py
eland/ndframe.py
eland/query_compiler.py
noxfile.py
setup.py

Closes #19
Now that `elasticsearch-py` v7.10 supports type hints we can remove a lot of `# type: ignore`

Support typed 'elasticsearch-py' and add 'py.typed'

---

eland/dataframe.py
eland/field_mappings.py
eland/groupby.py
eland/operations.py
eland/query.py
eland/query_compiler.py
eland/tests/dataframe/test_count_pytest.py
eland/tests/dataframe/test_groupby_pytest.py
eland/tests/dataframe/test_metrics_pytest.py
eland/tests/operations/test_map_pd_aggs_to_es_aggs_pytest.py

Closes #289 
Implemented
- `ed_df.groupby([...]).count()`
- `ed_df.groupby([...]).agg(['count'])`
- `ed_df.groupby([...]).agg(['max', 'min', 'count', 'mean'])` maintains order
- Fixed bug where following raises exception `ed_df.agg['count']`
- Added tests for all the above functionality
- Add `hacktoberfest-accepted` label
@sethmlarson Please Review :)

Implement `DataFrameGroupBy.count()`

---

.github/workflows/ci.yml
eland/field_mappings.py
eland/tests/dataframe/test_utils_pytest.py
noxfile.py

Closes #280 
@sethmlarson Please review 😄

es_type_overrides should error when receiving non-existing entries

---

eland/dataframe.py
eland/series.py
eland/tests/common.py
eland/tests/dataframe/test_repr_pytest.py
eland/tests/series/test_repr_pytest.py

Closes #305 
- Added the support for both DataFrame and series
- Added tests.
- I also added `**kwargs` to our `assert_test_*` methods because `check_less_precise` is now deprecated, we have to use `check_exact=False`
@sethmlarson Please review 😄

Add support for pd.set_option display.max_rows None

---

README.md
docs/sphinx/examples/demo_notebook.ipynb
eland/dataframe.py
eland/tests/tests_notebook/test_demo_notebook.ipynb

- Added the Elasticsearch Storage Usage to `df.info()`
Example:
```python
>>> ed_df = ed.DataFrame('localhost', 'flights')
>>> ed_df.info()
<class 'eland.dataframe.DataFrame'>
Index: 13059 entries, 0 to 13058
Data columns (total 27 columns):
---  ------              --------------  -----         
0   AvgTicketPrice      13059 non-null  float64       
1   Cancelled           13059 non-null  bool          
2   Carrier             13059 non-null  object        
3   Dest                13059 non-null  object        
4   DestAirportID       13059 non-null  object        
5   DestCityName        13059 non-null  object        
6   DestCountry         13059 non-null  object        
7   DestLocation        13059 non-null  object        
8   DestRegion          13059 non-null  object        
9 …
```

Add Elasticsearch storage usage to df.info()

---

.ci/run-elasticsearch.sh
.ci/test-matrix.yml
eland/groupby.py
eland/ml/ml_model.py
eland/ndframe.py
eland/plotting/_matplotlib/hist.py
noxfile.py
tests/common.py
tests/dataframe/test_metrics_pytest.py
tests/notebook/test_demo_notebook.ipynb
tests/series/test_metrics_pytest.py

Add support for Pandas 1.2.0

---

MANIFEST.in

Since we don't have `py.typed` in root directory
In `Manifest.in`
Either it should be included as part of `recursive-include eland`
or make it `include eland/py.typed`
I chose the second.
@sethmlarson Need thoughts on this.

Refactor manifest.in

---

README.md
docs/sphinx/reference/api/eland.DataFrame.es_info.rst
docs/sphinx/reference/api/eland.Series.es_info.rst
eland/__init__.py
eland/dataframe.py
eland/etl.py
eland/index.py
eland/ml/__init__.py
eland/ml/ml_model.py
eland/series.py
tests/ml/test_imported_ml_model_pytest.py
tests/ml/test_ml_model_pytest.py

Closes #330 
- This PR safely removes deprecations in eland
- Tests for `MLModel` are refactored safely.
@sethmlarson  Please review 😃 
This PR can be merged to master when required.

Remove deprecations

---

MANIFEST.in
docs/sphinx/reference/api/eland.DataFrame.mode.rst
docs/sphinx/reference/api/eland.Series.mode.rst
docs/sphinx/reference/dataframe.rst
docs/sphinx/reference/series.rst
eland/dataframe.py
eland/field_mappings.py
eland/groupby.py
eland/operations.py
eland/query.py
eland/query_compiler.py
eland/series.py
tests/dataframe/test_groupby_pytest.py
tests/dataframe/test_metrics_pytest.py
tests/series/test_metrics_pytest.py

Closes #215 
- Added mode to dataframe and series
- Added tests, documentation
- Currently mode isn't supported by `pandas groupby` too, Hence added a `NotImplementedError`
- To satisfy `mypy` I had to add type hints to some other methods too.
- Implemented es_size parameter instead of dumping the entire cluster if we have multiple mode values.
- Currently dropna=True is only supported because I have a query on `missing` parameter of terms aggregation
[Reference](https://github.com/elastic/eland/issues/215#issuecomment-725407371)
@sethmlarson Please review 😃

Add mode to dataframe and series

---

eland/operations.py
tests/dataframe/test_groupby_pytest.py

Closes #320 
- Groupby index in the result is now sorted similar to pandas.
- Added tests for groupby dropna=False
@sethmlarson Please review. 😃

Add sort order to groupby dropna=False

---

docs/sphinx/reference/api/eland.DataFrame.quantile.rst
docs/sphinx/reference/api/eland.Series.quantile.rst
docs/sphinx/reference/dataframe.rst
docs/sphinx/reference/series.rst
eland/dataframe.py
eland/operations.py
eland/query.py
eland/query_compiler.py
eland/series.py
tests/dataframe/test_metrics_pytest.py
tests/operations/test_map_pd_aggs_to_es_aggs_pytest.py
tests/series/test_metrics_pytest.py

Closes #315 
- Functionality w.r.t pandas for quantile is implemented i.e. `df.agg['quantile',...]` , `df.quantile()` , `Series.quantile()`
- Added tests and documentation.
@sethmlarson  Please Review 😄 
P.S. Need to change commit message while merging to master from `percentile` to `quantile` 😃

Add quantile to DataFrame and Series

---

eland/ml/ml_model.py
tests/dataframe/test_aggs_pytest.py
tests/dataframe/test_describe_pytest.py
tests/ml/test_ml_model_pytest.py
tests/series/test_arithmetics_pytest.py

So, There are around 184 deprecations because of the following:
- `check_less_precise` is deprecated and hence replaced it with `rtol` Ref: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.testing.assert_frame_equal.html
- `XGBClassifier` has deprecated `use_label_encoder` and we should keep it as `False` Ref: https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.XGBClassifier
- `Numpy` wants us to use `np.int_` instead of `np.int` Ref: https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated

Remove Warnings because of deprecations

---

docs/sphinx/reference/api/eland.groupby.DataFrameGroupBy.quantile.rst
docs/sphinx/reference/dataframe.rst
eland/groupby.py
eland/operations.py
eland/query_compiler.py
tests/dataframe/test_groupby_pytest.py

Closes #319 
Re used Most of the logic. 
@sethmlarson / @stevedodson Please review 
Ask jenkins to test this

Add quantile to dataframe groupby

---

eland/ndframe.py
eland/operations.py
eland/series.py
tests/dataframe/test_describe_pytest.py

Closes #316 
It's a small change to use internal logic and remove excessive code.
@sethmlarson / @stevedodson  Please review :)
Now the functionality for `describe` is enhanced to include `bool` fields as well.
```bash
>>> ed_df.describe() 
AvgTicketPrice     Cancelled  DistanceKilometers  DistanceMiles   FlightDelay  FlightDelayMin  FlightTimeHour  FlightTimeMin     dayOfWeek
count    13059.000000  13059.000000        13059.000000   13059.000000  13059.000000    13059.000000    13059.000000   13059.000000  13059.000000
mean       628.253689      0.128494         7092.142457    4406.853010      0.251168       47.335171        8.518797     511.127842      2.835975
std        266.407061      0.334664         4578.613803    2845.018714      0.433718       96.750415        5.579446 …
```

Optimize df.describe() to use Internal Logic rather than specific logic

---

eland/common.py
eland/etl.py
eland/plotting/_matplotlib/hist.py
requirements-dev.txt
setup.py

Closes #248,#359 
@sethmlarson / @stevedodson Please review :)
Ask jenkins to test this.

Add support to Pandas 1.3.0 and LightGBM 3.2.1

---

.ci/test-matrix.yml
.github/workflows/ci.yml
eland/common.py
eland/operations.py
noxfile.py
setup.py

Older versions are becoming harder to support, especially with pandas 1.2 dropping Python 3.6.

Drop support for Python 3.6, pandas<1.2

---

docs/sphinx/reference/api/eland.DataFrame.idxmax.rst
docs/sphinx/reference/api/eland.DataFrame.idxmin.rst
docs/sphinx/reference/dataframe.rst
eland/dataframe.py
eland/operations.py
eland/query.py
eland/query_compiler.py
noxfile.py
tests/dataframe/test_metrics_pytest.py

Work on #352 
- Implemented the pandas similar functionality
- Modified `noxfile.py` similar to `urllib3` because existing one is hanging on windows forever
@sethmlarson  or @stevedodson  Please review :)

Add idx to DataFrame

---

eland/arithmetics.py
eland/field_mappings.py
eland/query_compiler.py

The method `aggregatable_field_name` has `self._mappings_capabilities` which is a dataframe.
We are querying `dataframe`  4 times per method call. Instead query it once and reuse the result.
Also this improves readability of the code.
@sethmlarson  take a look

Optimize aggregate_field_name method in field_mappings

---

tests/ml/test_ml_model_pytest.py

Closes #251 
Also should we start supporting other learning parameters in https://xgboost.readthedocs.io/en/latest/parameter.html#learning-task-parameters ? Perhaps one by one.
such as 
- binary:logitraw
- binary:hinge

Add pseudohubererror in tests

---

eland/dataframe.py
eland/etl.py
eland/operations.py
eland/query_compiler.py
tests/dataframe/test_to_csv_pytest.py

This PR is a small change that removes `PandasToCSVCollector`, `PandasToDataFrameCollector` 
This has a basic functionality, But at the moment I think its not required. 
If any additional functionality comes, I think we can achieve it without a class!
@sethmlarson  Take a look at it :)

Remove `PandasToCSVCollector`, `PandasToDataFrameCollector` 

---

eland/operations.py
eland/query_compiler.py

Instead of yielding individual hits from `operations._search_yield_hits()` we should instead yield list of hits which are then sent through `_es_results_to_pandas` to transform a list of hits to a single dataframe. We do this mostly because post-processing is more efficient if done on larger dataframes instead of smaller single-hit ones.
Related to https://github.com/elastic/eland/pull/369 this will help performance because we won't be doing post-processing on individual dataframes.
cc @V1NAY8 @kxbin

Yield list of hits instead of individual hits

---

docs/sphinx/reference/api/eland.DataFrame.iterrows.rst
docs/sphinx/reference/api/eland.DataFrame.itertuples.rst
docs/sphinx/reference/dataframe.rst
eland/dataframe.py
eland/operations.py
eland/query_compiler.py
tests/dataframe/test_iterrows_itertuples_pytest.py

I'm sorry about this, because I want to squash multiple commits, and accidentally modified the branch name.
So that the PR was automatically closed unexpectedly.
For historical Conversation see PR #369
@sethmlarson  Thanks for your comment
Based on these suggestions, I have completed the modification, And passed the `lint` and `docs` jobs.
Thanks to this change in #379, no need to convert `_es_results_to_pandas` into a generator now, because they have similar effects.
Now, the performance has been further improved and the logic is more concise.
Finally, the same 50,000 data sets, my test results are as follows:
```
ed.iterrows(),  It took a total of `19 seconds` after the iteration
ed.itertuples(), It took a total of `15 seconds` after the iteration
ed.to_pandas(), It took `15 seconds` …
```

Add `iterrows()` and `itertuples()` DataFrame API, its usage is similar to `pandas`

---

.ci/Dockerfile

Since `dev-requirements.txt` is installed in `noxfile.py` we don't need to install it twice.

Speedup CI by only installing Nox  in Dockerfile

---

eland/dataframe.py
noxfile.py
setup.cfg

This PR will bump test coverage from 90% to 91% by excluding `NotImplementedError*`
Also we add `flynt` to nox format to ensure we use f-strings
@sethmlarson  take a look and hit Jenkins once.

Add flynt and add more excluded lines to improve coverage

---

bin/upload_hub_model.py
eland/ml/pytorch/__init__.py
eland/ml/pytorch/external_models.py
eland/ml/pytorch/pytorch_model.py
requirements-dev.txt
setup.py

This is a rough (and working) draft of porting PyTorch code into eland. This is the general shape of what I'm thinking of. It splits concerns into two - (1) generic PyTorch model management in Elasticsearch, and (2) interoperability with HuggingFace transformers and model hub.
Help and comments are welcome. There's surely a lot of formatting and general Python-ification that needs to happen still so help is welcome.

Adds PyTorch model management

---

eland/ml/_model_serializer.py
eland/ml/transformers/lightgbm.py

Work on #243 
I added `internal_count` for `lightgbm` 
@benwtrent Please take a look at this. Do we have a similar variable for `sklearn` and `xgboost` ?
Also should we add `leaf_count` for leaf_nodes ?
Sample JSON
```json
"tree_info": [
{
"tree_index": 0,
"num_leaves": 4,
"num_cat": 0,
"shrinkage": 1,
"tree_structure": {
"split_index": 0,
"split_feature": 3,
"split_gain": 21.871400833129883,
"threshold": -0.4775317725756382,
"decision_type": "<=",
"default_left": True,
"missing_type": "None",
"internal_value": -0.187661,
"internal_weight": 0,
"internal_count": 100,
"left_child": {
"leaf_index": 0,
"leaf_value": -0.25650466873000066,
"leaf_weight": 30,
"leaf_count": 30
},
"right_child": {
"split_index": 1,
"split_feature": 1,
"split_gain": 22.457199096679688,
"threshold": …
```

Add number_samples to lightgbm ML Model

---

README.md

The Machine Learning section now has two sub-sections — one for
traditional regression/classification and the other for NLP with
PyTorch. The examples show two ways to upload models from the Hugging
Face model hub.

Adds NLP with PyTorch basic example to README

---

eland/ml/pytorch/transformers.py

The padding parameter needs to be set on the tokenization call and not
in the constructor. Furthermore, the True value will only pad to the
largest input in a batch, however we don't trace with batches so this
value had no effect. The proper place to pass this parameter is in the
tokenization call itself and the proper value to use is "max_length"
which will pad the input to the maximum input size specified by the
model. Although we measure no functional or performance impact of this
setting, it has been suggested that this is a best practice.
See: https://huggingface.co/transformers/serialization.html#dummy-inputs-and-standard-lengths

Adds max_length padding to transformer tracing

---

eland/field_mappings.py
tests/dataframe/test_utils_pytest.py

This PR enables pandas columns that have been cast with a timezone to be automatically be converted to date.
Without this change, the default mapping would be used and an error would be thrown.

Add coverage for datetime columns with timezones

---

docs/guide/machine-learning.asciidoc

This PR adds a new subsection to the ML section of the Eland docs about NLP with PyTorch. The content of the addition is published in the repo [README](https://github.com/elastic/eland/blob/main/README.md#nlp-with-pytorch), still, it makes sense to add this bit to elastic.co in order to reach a wider audience.
[Machine learning](https://eland_428.docs-preview.app.elstc.co/guide/en/elasticsearch/client/eland/master/machine-learning.html)

[DOCS] Adds NLP with PyTorch section to ML-related page in Eland docs

---

bin/eland_import_hub_model

When using the `eland_import_hub_model` script with https and a self signed certificate it fails with the error
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)
```
The `verify_certs` should be set to false when creating the Elasticsearch client to work-around the problem.
Using a self-signed certificate might not be unusual for on prem users.
The change also removes a deprecation warning by switching from `timeout` to `request_timeout`

Add --insecure and --ca-cert options to the model hub upload script

---

eland/ml/ml_model.py
eland/ml/pytorch/_pytorch_model.py

Corrects 2 places where the type was either wrongly inferred or wrongly defined.
There errors popped up in #441 but since they are not strictly related to that change I thought it worth a new PR

Fix mypy type checker errors

---

docs/sphinx/reference/api/eland.Series.unique.rst
docs/sphinx/reference/series.rst
eland/operations.py
eland/query_compiler.py
eland/series.py
tests/series/test_metrics_pytest.py

Closes #446 
@sethmlarson Please have a quick review :)
Happy to do any further changes required.

Add Eland Series unique

---

requirements-dev.txt
requirements.txt
setup.py

Dependencies weren't matching between `setup.py` and `requirements.txt`/`requirements-dev.txt`. 
This PR aligns them to match, and locks the dependency version to the current major where a version was previously specified.
Note: 
`scikit-learn` was locked to versions lower than `1.0.0` in `setup.py`, but it was open-ended on the high side in `requirements-dev.txt`. At the time this PR was raised, the latest version is `1.0.2`, which is why I locked the max version `<2`.

Align dependencies between requirement files and setup.py

---

bin/eland_import_hub_model
eland/ml/pytorch/_pytorch_model.py

Switched from `print` statements to `logging` for a cleaner and more informative output - timestamps and log level are shown. The logging is now a bit more verbose, but it will help users to better understand what the script is doing.
Instead of being limited to passing credentials in the URL, there are now 2 additional methods:
- username/password using `--es-username` and `--es-password`
- API key using `--es-api-key`
Credentials can also be specified as environment variables with `ES_USERNAME`/`ES_PASSWORD` or `ES_API_KEY`
In order to use the `eland_import_hub_model` script, PyTorch extras are required to be installed. If the user does not have the required packages installed, a helpful message is logged with a hint to install `eland[pytorch]` with `pip`.
If a trained model with the …

Hub model import script improvements

---

bin/eland_import_hub_model

The Cloud ID simplifies sending data to a cluster on Elastic Cloud.
With this change, the user will have the option specify a Cloud ID using the `--cloud-id` argument as an alternative to an Elasticsearch URL (`--url` argument).
`--cloud-id` and `--url` are mutually exclusive arguments.

Add support for Cloud ID to hub model import script

---

bin/eland_import_hub_model
eland/ml/pytorch/nlp_ml_model.py
eland/ml/pytorch/transformers.py

Adds support for `question_answering` NLP models within the pytorch model uploader.
Related: https://github.com/elastic/elasticsearch/pull/85958

[ML] add support for question_answering NLP tasks

---

eland/ml/pytorch/__init__.py
eland/ml/pytorch/traceable_model.py
eland/ml/pytorch/transformers.py
tests/ml/pytorch/test_pytorch_model_upload_pytest.py
tests/ml/pytorch/test_transformer_pytorch_model_pytest.py

This improves the user consumed functions and classes for PyTorch NLP model upload to Elasticsearch.
Previously it was difficult to wrap your own module for uploading to Elasticsearch.
This commit splits some classes out, adds new ones, and adds tests showing how to wrap some simple modules.

[ML] improve general pytorch model import and add tests

---

eland/ml/ml_model.py
eland/ml/transformers/sklearn.py
tests/ml/test_ml_model_pytest.py

This switches our sklearn.DecisionTreeClassifier serialization logic to account for multi-valued leaves in the tree.
The key difference between our inference and DecisionTreeClassifier, is that we run a `softMax` over the leaf where sklearn simply normalizes the results.
This means that our "probabilities" returned will be different than sklearn.

[ML] fixes decision tree classifier upload to account for probabilities

---

docs/guide/machine-learning.asciidoc

Relates to https://github.com/elastic/elasticsearch/pull/85958
This PR adds the `question_answering` task type to the details about the eland_import_hub_model script in https://www.elastic.co/guide/en/elasticsearch/client/eland/current/machine-learning.html#ml-nlp-pytorch

[DOCS] Add question_answering NLP task type

---

docs/guide/index.asciidoc

Relates to https://github.com/elastic/eland/pull/467, which encounters the following documentation build error due to the lack of a "branch" attribute:
> 13:26:19 INFO:build_docs:Bad cross-document links:
13:26:19 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/eland/current/machine-learning.html contains broken links to:
13:26:19 INFO:build_docs:   - en/machine-learning/{branch}/ml-nlp-model-ref.html

[DOCS] Include missing attributes

---

requirements-dev.txt
setup.py

Version 8.3 of the elastic stack uses PyTorch 1.11 (https://github.com/elastic/ml-cpp/pull/2238) this changes the required version to match

Bump PyTorch version to 1.11

---

bin/eland_import_hub_model
eland/ml/pytorch/__init__.py
eland/ml/pytorch/transformers.py
tests/ml/pytorch/test_transformer_pytorch_model_pytest.py

For many model types, we don't need to require the task requested. We can infer the task type based on the model configuration and architecture. 
This commit makes the `task-type` parameter optional for the model up load script and adds logic for auto-detecting the task type based on the 🤗 model.

[ML] adds new auto task type that attempts to automatically determine NLP task type from model config

---

.dockerignore

Makes the `.dockerignore` file more restrictive by matching what is in `.gitignore`. Of particular note is the exclusion of virtual environments can be large

Add more exclusions to the dockerignore file

---

README.md
eland/ml/pytorch/_pytorch_model.py
noxfile.py
requirements-dev.txt
requirements.txt
setup.py

PyTorch recently released [version 1.12](https://github.com/pytorch/pytorch/releases/tag/v1.12.0) which contains breaking changes to torchscript models making them incompatible with earlier versions. 
The Elastic stack uses version 1.11 of the PyTorch C++ library (libtorch), a model traced to torchscript format using a v1.12 Python PyTorch install cannot be evaluated in libtorch v1.11. 
Anyone using Eland to import a model into Elastic today would pull the latest version of PyTorch and find the model cannot be evaluated in Elasticsearch. Opening the model errors with the message: 
`Attempted to read a PyTorch file with version 10, but the maximum supported version for reading is 9. Your PyTorch installation may be too old.` 
This change to the requirements prevents Eland using v1.12 of …

Restrict PyTorch version not to be more advanced than that used in Elasticsearch 

---

eland/ml/pytorch/nlp_ml_model.py
eland/ml/pytorch/transformers.py

Adds text_similarity task support. This is a cross-encoder transformer task where both sequences are given to the transformer at once. 
According to 🤗 (or at least how the cross-encoder models are concerned) this is a sequence classification task with just one classification "label". But really, it isn't labeled at all and is more akin to a regression model.
related: https://github.com/elastic/elasticsearch/pull/88439

[ML] add text_similarity task support

---

eland/ml/transformers/__init__.py

In some environments simply importing the `TransformerModel` class used to configure NLP models can generate an error in an unrelated dependency:
```
from eland.ml.pytorch.transformers import TransformerModel
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File " /source/eland/eland/ml/__init__.py", line 18, in <module>
from eland.ml.ml_model import ImportedMLModel, MLModel  # noqa: F401
File " /source/eland/eland/ml/ml_model.py", line 27, in <module>
from .transformers import get_model_transformer
File " /source/eland/eland/ml/transformers/__init__.py", line 83, in <module>
from .lightgbm import _MODEL_TRANSFORMERS as _LIGHTGBM_MODEL_TRANSFORMERS
File " /source/eland/eland/ml/transformers/lightgbm.py", line 25, in <module>
import_optional_dependency("lightgbm", …
```

Handle OSError for missing LightGBM dependency

---

eland/ml/pytorch/transformers.py

Fixes a problem reported in https://discuss.elastic.co/t/loading-bert-model/327709

[NLP] Prevent TypeError with None check

---

eland/ml/pytorch/transformers.py

The `pass_through` task returns the models output directly without any post-processing of the results. `pass_through` is typically used for debugging. 
This change allows models to be loaded into Elasticsearch with the `pass_through` task
An example invocation of the `eland_import_hub_model` script with `pass_through` is: 
```
eland_import_hub_model \
--url XXX \
-u XXX -p XXXX \
--hub-model-id "sentence-transformers/msmarco-MiniLM-L-12-v3" \
--task-type pass_through 
```

[NLP] Add support for the pass_through task

---

eland/ml/pytorch/nlp_ml_model.py
eland/ml/pytorch/traceable_model.py
eland/ml/pytorch/transformers.py
tests/ml/pytorch/test_transformer_pytorch_model_pytest.py

elastic/elasticsearch#95176 added the `embedding_size` field to text embedding model configs. The field is set at creation and cannot be changed.  
This change now sets `embedding_size` when creating the config for text embedding models. The embedding size is found by evaluating the model and taking the length of the last dimension of the output tensor

Set embedding size for Text Embedding models

---

requirements-dev.txt
requirements.txt
setup.py

Tests are failing with the error 
```
E           AttributeError: module 'numpy' has no attribute 'bool'.
E           `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
E           The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
E               https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
```
This is coming from the Shap explainer code using the deprecated `np.bool` attribute. 
```
.nox/test-3-10-pandas_version-1-5-0/lib/python3.10/site-packages/shap/explainers/_tree.py:384: in shap_values …
```

Use compatible versions of numpy and shap

---

requirements-dev.txt
requirements.txt
setup.py

Follow up to #539 this adds a comment explaining why the NumPy versions has been limited and sets a lower bound

Limit NumPy to a range of versions and add note

---

bin/eland_import_hub_model
eland/ml/pytorch/transformers.py
tests/ml/pytorch/test_transformer_pytorch_model_pytest.py

The `eland_import_hub_model` script supports uploading a local file where the `--hub-model-id` argument is a file path. 
If the `--es-model-id` option is not used the model Id is generated from the hub model id and when that is a file path the path must be converted to a valid elasticsearch model id.
- Replace whitespace, forward slash and back slash with double underscore '__'
- Lower case
- Left truncated to 64 chars

Generate valid model id from file path

---

eland/ml/pytorch/transformers.py

The `es_version` parameter to `TransformerModel` is optional but missing a default value.

Default the optional es_version parameter

---

docs/requirements-docs.txt
docs/sphinx/conf.py

The pydata-sphinx-theme is failing, leading to our RTD being unusable. Switching to Furo appears to work just fine, let's switch to this for now to get the docs usable again.

Switch to the 'Furo' Sphinx theme

---

bin/eland_import_hub_model
eland/ml/pytorch/transformers.py

Relates https://github.com/elastic/eland/pull/552
**Issue**:
For migration from [scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) to [console_scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) in `setup.py`, the current long `if __name__ == "__main__":` section is a blocker because the console_scripts requires to specify a function as an entrypoint.
**Solution**:
I'm encapceling the current main logic into `main()` function through this PR.

Minimize if main section

---

bin/eland_import_hub_model
eland/ml/pytorch/transformers.py

Relates https://github.com/elastic/eland/pull/552
**Issue**:
`eland_import_hub_model` claims `ModuleNotFoundError` unless pytorch is installed.
```
Traceback (most recent call last):
File "/usr/local/bin/eland_import_hub_model", line 34, in <module>
import torch
ModuleNotFoundError: No module named 'torch'
```
**Appropriate result**:
`eland_import_hub_model` should show instruction what is missing like this.
```
2023-06-30 03:52:36,956 ERROR : Failed to run because module 'tqdm' is not available.
This script requires PyTorch extras to run. You can install these by running:
/usr/local/bin/python -m pip install 'eland[pytorch]'
```
**How to repro**:
```
docker run -it python:3 bash -c "pip install git+https://github.com/elastic/eland.git@main && /usr/local/bin/eland_import_hub_model --help" …
```

Fix No module named 'torch'

---

eland/ml/pytorch/transformers.py

We were attempting to load SentenceTransformers by looking at the model prefix, however SentenceTransformers can also be loaded from other orgs in the model hub, as well as from local disk. This prefix checking failed in those two cases. To simplify the loading logic and deciding which wrapper to use, we’ve removed support for text_embedding tasks to load a plain Transformer. We now only support DPR embedding models and SentenceTransformer embedding models. If you try to load a plain Transformer model, it will be loaded by SentenceTransformers and a mean pooling layer will automatically be added by the SentenceTransformer library. Since we no longer automatically support non-DPR and non-SentenceTransformers, we should include somewhere example code for how to load a custom model without …

Simplify embedding model support and loading

---

Dockerfile

Closes #585 
When upgrading to Debian 12 Bookworm, I've hit https://pythonspeed.com/articles/externally-managed-environment-pep-668/ and got Python 3.11 which isn't supported yet by Eland so I decided to use the Python 3.10 official image instead. It does not offer date-based tags, so I followed https://snyk.io/blog/best-practices-containerizing-python-docker/ and pinned using the sha256 digest instead.
I've used the README to test that this was still working, including:
* Calling eland_import_hub_model to load elastic/distilbert-base-cased-finetuned-conll03-english on an Elastic Cloud cluster. I then started it on Kibana and tested that it worked as expected on short sentences.
* Using the DataFrame API to reproduce the various examples.
* Fitting a XGBoost classifier locally, importing …

Update Docker image to Debian 12 Bookworm

---

README.md

* Using `basic_auth` prints the following warning since elasticsearch-py 8.0:
```python
DeprecationWarning: The 'http_auth' parameter is deprecated. Use 'basic_auth' or 'bearer_auth' parameters instead
```
* Using "localhost:9200" fails outright since elasticsearch-py 8.0. I wasn't sure if `http` or `https` should be used, but the rest of the repo uses `http`.
```python
ValueError: URL must include a 'scheme', 'host', and 'port' component (ie 'https://localhost:9200')
```
* The XGBoost section assumes `training_data` exists: let's help users by creating it for them.

Fix README so that copy/pastes work without warnings

---

README.md

You can see the result here: https://github.com/pquentin/eland/tree/badge-url.

Fix downloads badge URL

---

Dockerfile

This reverts commit 0be509730a8d78d453fd7fb12149852c5552050f. It requires an up-to-date Docker/libseccomp version and breaks the image build for some users.
We can add this back when we start publishing an Eland Docker image.

Revert "Update Docker image to Debian 12 Bookworm (#586)"

---

.buildkite/release-docker/pipeline.yml
catalog-info.yaml

The idea is to get the scaffolding in place before testing the pipeline itself. This also declares the existing pipeline in the repository itself, according to latest Buildkite good practices at Elastic.

Add dummy pipeline to prepare publishing a Docker image

---

eland/field_mappings.py

This is related to issue #580 
In some scenarios (a limited-scope API key, or maybe a corporate environment) a user of `eland` might not have enough permissions to determine the host's Elasticsearch version.
In that case, we could default to using the workaround, to be sure.

Use the workaround if we can't determine the server's version

---

eland/field_mappings.py

This PR fixes another of the more easy-to-squash deprecations for when `eland` might start supporting `pandas>=2.0.0`.

Fix iteritems deprecation in pandas

---

docs/guide/machine-learning.asciidoc
eland/cli/eland_import_hub_model.py
eland/ml/pytorch/transformers.py

Tested by:
* Forking `elastic/distilbert-base-cased-finetuned-conll03-english` to a private repo
* Running `eland_import_hub_model` using `--hub-access-token` and `HUB_ACCESS_TOKEN`
* In Kibana, synchronize, start and test the model with success.
I have not tested other task types, to do that I would need help to know what models to use in each case.

Allow importing private HuggingFace models

---

tests/series/test_arithmetics_pytest.py

This removes the deprecated `check_less_precise` argument from one of the unit tests.
Part of the necessary adjustments to maybe start supporting `pandas>=2.0.0`

Remove deprecated check_less_precise

---

Dockerfile

This is a PR coming from [this snyk alert](https://app.snyk.io/org/clients-team/project/3125ecc2-6747-49be-86be-b47c7b05390d#issue-SNYK-DEBIAN11-GCC10-5901313) regarding [CVE-2023-4039](https://nvd.nist.gov/vuln/detail/CVE-2023-4039). It updates the Dockerfile using the latest image.

[CVE-2023-4039] Updated bullseye docker image

---

.buildkite/release-docker/pipeline.yml
.buildkite/release-docker/run.sh
.readthedocs.yml
Dockerfile
eland/dataframe.py
eland/ml/_optional.py
setup.py
utils/generate-supported-apis.py

Closes #407
Here's a successful build: https://buildkite.com/elastic/eland-release-docker/builds/9#018af52e-7ca0-4e9c-8aa5-6fd9cd4348de. This also reintroduces https://github.com/elastic/eland/pull/586, using a slim Debian 12 base image, which will greatly reduce the noise from vulnerability scanners.
I've left #600 as future work.

Add Buildkite pipeline to push Docker image

---

.buildkite/release-docker/run.sh
Dockerfile

Closes #600 
This was done by using the torchcpu PyPI package and not storing the PyPI cache in the Docker image.
Tested using `docker run -it --rm --network host -e ES_USERNAME=$ES_USERNAME -e ES_PASSWORD=$ES_PASSWORD eland eland_import_hub_model --cloud-id $CLOUD_ID  --hub-model-id elastic/distilbert-base-cased-finetuned-conll03-english --task-type ner`

Reduce Docker image size from 4.8GB to 2.2GB

---

eland/field_mappings.py

I have been trying using `eland` with `pandas>2`. This is one of the minor changes I had to make to prepare for the removal of the `is_datetime_or_timedelta_dtype` utility.
More pull requests might be coming, but I try to keep them as small as possible.

Prepare for deprecation of is_datetime_or_timedelta_dtype in Pandas 2.0

---

eland/ml/pytorch/transformers.py
noxfile.py
requirements-dev.txt
tests/ml/pytorch/test_pytorch_model_upload_pytest.py

Fix direct usage of TransformerModel

---

tests/etl/test_pandas_to_eland.py

Use _append instead of append since it's still available after pandas 2.0.0

---

tests/dataframe/test_groupby_pytest.py

Pandas 2 has removed the `mad` aggregation. To be able to test whether eland's version produces the correct result, we can implement it ourselves, just for the tests.
Of course I'm open to other ideas (skipping the metric if we are in Pandas 2 perhaps?).
Related pandas issue: https://github.com/pandas-dev/pandas/issues/11787
Related to #601

Deal with the mad aggregation being removed in Pandas 2

---

.buildkite/run-elasticsearch.sh
CONTRIBUTING.md
eland/ml/pytorch/traceable_model.py
eland/ml/pytorch/transformers.py
tests/ml/pytorch/test_pytorch_model_config_pytest.py
tests/ml/pytorch/test_pytorch_model_upload_pytest.py

This PR adds an ability to estimate per deployment and per allocation memory usage of NLP transformer models. It uses `torch.profiler` and performs logs the peak memory usage during the inference.
This information is then used in Elasticsearch to provision models with sufficient memory (elastic/elasticsearch#98874).

[ML] Better memory estimation for NLP models

---

catalog-info.yaml

@leemthompo had to include an useless commit to trigger CI here: https://github.com/elastic/eland/pull/630. For the record, in cases like that I tend to use `git commit --allow-empty -m "Trigger CI"` which does not change the content of the pull request.

Allow es-doc members to trigger CI

---

tests/ml/pytorch/test_pytorch_model_config_pytest.py

Skip failing model config tests

---

eland/ml/common.py
eland/ml/ml_model.py
tests/ml/test_ml_model_pytest.py

This PR adds support for importing a model with a specific `inference_config`. This allows us to use regression models with the `learning_to_rank` inference type that come with externally supplied configuration.
Example:
```python
MLModel.import_model(
es_client,
model_id,
regressor,
feature_names,
es_if_exists="replace",
es_compress_model_definition=compress_model_definition,
inference_config={
"learning_to_rank": {
"feature_extractors": [
{
"query_extractor": {
"feature_name": "title_bm25",
"query": {"match": {"title": "{{query_string}}"}},
}
},
{
"query_extractor": {
"feature_name": "imdb_rating",
"query": {
"script_score": {
"query": {"exists": {"field": "imdbRating"}},
"script": {"source": 'return doc["imdbRating"].value;'},
}
},
}
},
]
}
},
)
```
The change is backward compatible - …

Accept LTR inference config when creating model

---

eland/ml/ltr/__init__.py
eland/ml/ltr/feature_logger.py
eland/ml/ltr/ltr_model_config.py
eland/ml/ml_model.py
tests/ml/ltr/test_feature_logger_pytest.py
tests/ml/test_ml_model_pytest.py

This PR contains two improvements for the LTR feature in Eland.
- Feature logger now extract `NaN` when a query does not match a query. It is consistent with what is done in Elasticsearch.
- A specific method (`import_ltr_model`) has been added to import LTR model with support for a `ltr_model_config` object of class `LTRModelConfig`. The `inference_model` params is removed from the `import_model` method
**Example:**
```python
ed.ml.MLModel.import_ltr_model(
es_client=es_client,
model=ranker,
model_id='ltr-model-xgb',
ltr_model_config=ltr_model_config,
es_if_exists = 'replace'
)
```
The previous version was more difficult to use (and could lead to inconsistencies):
```python
ed.ml.MLModel.import_model(
es_client=es_client,
model=ranker,
model_id='ltr-model-xgb', …
```

LTR improvements

---

docs/sphinx/examples/online_retail_analysis.ipynb

Test notebook on this PR branch:
[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/elastic/eland/blob/65b2cac09d8958a0865e648f66dbc7fdf48176e5/docs/sphinx/examples/online_retail_analysis.ipynb)
- Add Open in Colab button
- Download dataset
- Use Client with Cloud instance, get pass for credentials
🔍 [Visual diff](https://github.com/elastic/eland/assets/32779855/7f8ac2a1-88e9-4959-8b3b-f1b87cc5217f)
- Fixed in https://github.com/elastic/eland/pull/641/commits/5dd1574db172db853882092ea28ebd2931fc3398 by replacing with `df[(df['Quantity'] > 50) & (df['UnitPrice'] < 100)]`. See [here](https://github.com/elastic/eland/pull/641/commits/5dd1574db172db853882092ea28ebd2931fc3398#diff-b08d82964587ad4175ba2e474d2e72cb31531948e50f5181 …

[DOCS] Make online retail notebook runnable in Colab

---

eland/ml/_model_serializer.py
eland/ml/transformers/xgboost.py
tests/ml/test_ml_model_pytest.py

When exporting XGBoost trees to ES, it was assumed are always using the left branch of the tree. 
In fact it is false and it is needed to configure it using a conditional on `default_left`.
Tests have been updated to check predicted score in _search match the one from the ranker model. It should allows us to catch any problem like this in the future.

Fix missing value support for XGBRanker.

---

.buildkite/pull-requests.json

This will avoid having to run `buildkite test this please` in all pull requests created from forks by members of the elastic organization.

Run Buildkite docs jobs in pull requests from forks

---

eland/cli/eland_import_hub_model.py
eland/ml/pytorch/__init__.py
eland/ml/pytorch/transformers.py
tests/ml/pytorch/test_pytorch_model_config_pytest.py

The error in #668 is due to the model's max input length being incorrectly set to a value that is larger than the true max input length. The problem is due to falling back to the `max_position_embeddings` setting if `model_max_length` is not found in the config. `max_position_embeddings` cannot be reliably used to set the max input size as it may be greater than the true max input. 
For the situations where the max input length cannot be found in the model's configuration a new `--max-model-input-length` setting is added to the `eland/cli/eland_import_hub_model`  script allowing the user to manually specify the value. This is an advanced setting and requires the user to knowingly set an accurate value. It is valid to set a smaller value and input will be truncated to that smaller value. …

Fix error finding the model's max input size and add override option

---

docs/guide/overview.asciidoc

Same fix as in https://github.com/elastic/elasticsearch-py/pull/2477 for the one reference to the API Key tuple in the Eland documentation

Update overview.asciidoc to replace tuple reference to API Key

---

docs/guide/machine-learning.asciidoc
eland/cli/eland_import_hub_model.py

Depends on #667 
Tested by running `python -m dummyserver.proxy` using tag 2.1.0 of urllib3 (I broke the command-line proxy in later commits of urllib3) and using `export HTTPS_PROXY=http://localhost:8888/` to upload a model with Eland. Without the proxy running, the upload fails.

Support HTTP proxies in eland_import_hub_model

---

.readthedocs.yml
docs/requirements-docs.txt
noxfile.py
requirements-dev.txt
requirements.txt
setup.py

Today we specify `elasticsearch>=8.3,<9` in four places. In setup.py, as expected for the package metadata to be correct, but also:
* in requirements.txt, which was unused, so I removed it
* in requirements-dev.txt, which can simply refer to `.[extras]` to install all packages with its extras
* in noxfile.py, where installing `.` is enough to make lint pass (also we don't need pre-releases anymore)
* in docs/requirements-docs.txt which was out of date anyway

Stop duplicating requirements

---

eland/ml/pytorch/transformers.py

Eland still supports Python 3.8, so str.removeprefix can be called and raise an `AttributeError`.
Once Eland drops Python 3.8 support this if/else can be removed (only keeping the code in the if).

Fix missing method str.removeprefix in Python 3.8

---

eland/cli/eland_import_hub_model.py

As reported in #696 serverless clusters always return version `8.11.0` which makes the model upload script think that it does not support the upgraded version of PyTorch. The fix is to check for  `build_flavor == serverless`
Closes #696

Make model upload compatible with serverless clusters

---

README.md

All the other occurrences of `eland[pytorch]` use quotes already.

Quote eland[pytorch] for ZSH users

---

eland/operations.py

While running the new release, it looks like my previous pull request #693 didn't deal with an edge case while checking whether a field was present. It is possible for a field to be a list of dicts as well.
On top of that it feels a bit like painting myself into a corner fixing the missing fields #692. The example indices eland uses for testing aren't as complex (and nested) as the mappings I'm dealing with in our internal data warehouse.

Deal with the possibility of lists in multi-fields

---

.buildkite/pipeline.yml
eland/cli/eland_import_hub_model.py
eland/common.py
eland/ml/ml_model.py
tests/__init__.py
tests/ml/test_ml_model_pytest.py

In Elasticsearch >= 8.15.0, we update the `PUT _ml/trained_models/<model_id>` API for LTR models and specifying `input.field_names` is not supported anymore. 
Previously, the field was required and eland was putting feature names into it as a hack.
The Elasticsearch PR: https://github.com/elastic/elasticsearch/pull/109437
The behavior now depends of the es version and the `input.field_names` is set only for ES < 8.15.0

Remove input fields from exported LTR models

---

eland/ml/pytorch/transformers.py
tests/ml/pytorch/test_pytorch_model_config_pytest.py

NLP models have 3 truncation settings: `FIRST`, `SECOND` and `NONE`
`FIRST` means truncate the first input. In most cases there is only 1 input (e.g for text embeddings) so this is a sensible default.
`SECOND` means truncate the second input. Task types with 2 inputs are extractive question answering where the question is one input and the context the other. Text Similarity takes has 2 inputs.
`NONE` means don't truncate and window the input.
For text similarity the first input is usually the shorter input, for example it might be the query text in a rerank operation. In this situation it is better to truncate the second input. This change makes that the default.

Default truncation to `second` for text similarity

---

eland/cli/eland_import_hub_model.py

As reported in #712 several people have tried to use `--task-type rerank` to upload a reranking model to Elasticsearch where `--task-type text_similarity` should be used. This change adds a message to `eland_import_hub_model` help to use `--task-type text_similarity` for reranking and adds the same information to the error message produced when the `--task-type` argument fails validation. 
There isn't a straight forward extension point to change the error message produced by ArgParse when the argument as a set of valid choices. Catching and checking the `ArgumentError` is the best option I could see. 
Closes #712

Add note about using text_similarity task for rerank to the import model CLI

---

Dockerfile

The main motivation is to reduce the number of CVEs. Using trivy, I'm seeing 863 system vulnerabilities in 8.15.0, which is based on Debian 12.
```
docker.elastic.co/eland/eland:8.15.0 (debian 12.6)
==================================================
Total: 863 (UNKNOWN: 1, LOW: 261, MEDIUM: 517, HIGH: 78, CRITICAL: 6)
```
With Wolfi, those CVEs are all gone:
```
eland (chainguard 20230214)
===========================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
Additionally, the ARM image went from 1.66GB to 1GB (I don't have Linux x86-64 numbers).
However, we still have the following CVEs about our immediate dependencies. Fixing them is future work:
```
Python (python-pkg)
===================
Total: 6 (UNKNOWN: 0, LOW: 1, MEDIUM: 1, HIGH: 3, CRITICAL: 1) …
```

Migrate to Wolfi base Docker image

---

.buildkite/release-docker/run.sh
Dockerfile
Dockerfile.wolfi

Since non-latest Wolfi images are not public, we allow users to continue building with Dockerfile being Debian-based.

Restore public Dockerfile

---

eland/cli/eland_import_hub_model.py
eland/ml/pytorch/transformers.py
noxfile.py
setup.py
tests/ml/pytorch/test_pytorch_model_config_pytest.py
tests/ml/pytorch/test_pytorch_model_upload_pytest.py

Elasticsearch has upgraded to PyTorch to 2.3.1 in 8.16 and 8.15.2. This PR updates Eland to use the same version.
The usual compatibility issues apply, Eland will refuse to upload to an Elasticsearch cluster that has is using an earlier version of PyTorch. The range of compatible versions of Sentence Transformers and HuggingFace Transformers has been updated to incorporate the latest release of the same major version. 
Elasticsearch is upgraded in https://github.com/elastic/ml-cpp/pull/2705

Upgrade PyTorch to version 2.3.1

---

.buildkite/build-docker-images.sh
.buildkite/pipeline.yml
Dockerfile
Dockerfile.wolfi

I tested the Docker image buid on macOS, which does not need a version. And I failed to test a staging build + push on Buildkite before releasing, sorry.
This will require a new release, Eland 8.15.2.

Fix Docker image build on Linux

---

eland/ml/pytorch/nlp_ml_model.py
eland/ml/pytorch/transformers.py

This PR adds support for uploading models based on DeBERTa-V2 and V3.
Unfortunately there's currently no way test test this, due to an incompatibility between the Huggingface DeBERTa model and our pytorch implementation https://github.com/huggingface/transformers/issues/20815

Add support for DeBERTa-V2 tokenizer

---

Dockerfile.wolfi

The config/certs directory of Elasticsearch is not readable by other users and groups. This work in the public image, which uses the root user, but the Wolfi image does not. Using the same user id fixes the problem.
Thanks @legacyworld for the report.

Allow reading Elasticsearch certs in Wolfi image

---

Dockerfile.wolfi

Reverts elastic/eland#732. Setting a different user actually breaks model upload, as Hugging Face writes to a cache folder unconditionally (even with caching disabled: https://huggingface.co/docs/datasets/v2.17.1/en/package_reference/main_classes#datasets.disable_caching). In my tests with `--ca-certs` I only checked that we could read the cert, unfortunately.

Revert "Allow reading Elasticsearch certs in Wolfi image"

---

eland/__init__.py
eland/common.py
eland/ml/exporters/es_gb_models.py

Introduce a warning indicating that exporting data frame analytics models as ESGradientBoostingModel subclasses is deprecated and will be removed in version 9.0.0.
The implementation of ESGradientBoostingModel relies on importing undocumented private classes that were changed in 1.4 to https://github.com/scikit-learn/scikit-learn/pull/26278. This dependency makes the code difficult to maintain, while the functionality is not widely used by users. Therefore, we will deprecate this functionality in 8.16 and remove it completely in 9.0.0.

Add deprecation warning for ESGradientBoostingModel subclasses

---

Dockerfile
eland/ml/pytorch/transformers.py

This is essentially the same PR as #706 but I fixed formatter issue.
---
This pull request introduces a new model type for text expansion and refines error messaging for unsupported task types. The most important changes include the addition of the `_TraceableTextExpansionModel` class and updates to the `_create_traceable_model` method to handle this new model type.
* Added the `_TraceableTextExpansionModel` class with a `_prepare_inputs` method to handle text expansion tasks. (`eland/ml/pytorch/transformers.py`)
* Updated the `_create_traceable_model` method to include logic for creating a `_TraceableTextExpansionModel` when the task type is "text_expansion". (`eland/ml/pytorch/transformers.py`)
* Refined the error message in `_create_traceable_model` to clarify that the task type must …

Expansion support

---

.buildkite/Dockerfile
.buildkite/build-documentation.sh
.dockerignore
docs/sphinx/reference/api/eland.DataFrame.to_json.rst
docs/sphinx/reference/api/eland.ml.MLModel.rst

This will respect the PYTHON_VERSION setting, allowing us to remove support for Python 3.8.
This was noticed by @bartbroere when working on #742. Thank you!

Build documentation using Docker again

---

.buildkite/pipeline.yml
.readthedocs.yml
CONTRIBUTING.md
README.md
docs/guide/overview.asciidoc
docs/sphinx/development/contributing.rst
eland/ml/pytorch/transformers.py
noxfile.py
setup.py

This PR is somewhat related to #742 . It's also part of my bigger effort of getting eland and its dependencies more up to date. Currently introducing eland as a dependency in a project means you're stuck at Pandas<2 and therefore also Python<3.13 (pandas 1.5.0 doesn't build on Python 3.13).
It updates the package so it supports newer Python versions.

Drop Python 3.8 support and introduce Python 3.12 CI/CD

---

.buildkite/Dockerfile

We can revert when https://github.com/wntrblm/nox/issues/930 is fixed.

Pin nox to avoid session.env issue

---

.buildkite/Dockerfile
noxfile.py

See the linked nox issues for more details.
Turns out `subprocess` was not needed, and giving all files to mypy is much faster than running mypy once per file.

Allow nox 2025.02.09

---

eland/ml/pytorch/transformers.py
setup.py

Fixes a kernel crash importing https://huggingface.co/BAAI/bge-m3 as described in #737
The required change is upgrading the version of transformers.
```
eland_import_hub_model \
--url 'http://localhost:9200' \
-u elastic-admin -p elastic-password \
--hub-model-id 'baai/bge-m3' \
--task-type text_embedding --insecure --max-model-input-length=8192
```

Fix tracing baai/bge-m3

---

docs/reference/machine-learning.md

Related issue: https://github.com/elastic/eland/issues/764

[DOCS] Clean up CLI examples in ML docs

---

CHANGELOG.rst
eland/_version.py

Reverts elastic/eland#771. The pull request was against main, not 8.18. The main branch is for the 9.x releases.
Regarding 8.18.0 itself, I yanked the release from PyPI and deleted the tag from git a few minutes after releasing. This will avoid anyone using the `main` branch and thinking it's 8.18.0.

Revert "Release 8.18.0"

---

noxfile.py

PyTorch 2.3.1 does support Python 3.12.

Run PyTorch tests on 3.12 too

---

.buildkite/pipeline.yml
eland/ml/_model_serializer.py
tests/ml/test_ml_model_pytest.py

Backport to `8.x` from #777 
Adds the 8.19.0-SNAPSHOT to the build.
Fixes a bug in the tests:
The LTR rescoring in Elasticsearch 8.19+ has the ability to normalize the scores for LTR if any score is negative (as Lucene cannot handle negative scores). This updates the model tests to ensure scores are normalized as well.
The normalization process essentially adds the negative score to all scores, sliding the scoring window upwards, so that all scores are >= 0.0

Add 8.19.0 Snapshot to Build and Fix test_ml_model Tests to Normalized Expected Scores if Min Score is Less Than Zero

---

tests/ml/test_ml_model_pytest.py

Follow on to https://github.com/elastic/eland/pull/777
Now that the LTR rescoring bounded window fix will be in 9.0.1 [via this PR](https://github.com/elastic/elasticsearch/pull/127345), this adds 9.0.1+ to the condition to check to see if the test needs to rescore the expected scores.

Add 9.0.1 check for LTR rescoring for tests

---

Dockerfile
Dockerfile.wolfi
setup.py

PyTorch was upgraded to 2.5.1 in ml-cpp on the 8.18 and 9.0 branches in https://github.com/elastic/ml-cpp/pull/2800
The backport of this will require this version check to be updated https://github.com/elastic/eland/blob/main/eland/cli/eland_import_hub_model.py#L242

Upgrade PyTorch to 2.5.1

---

tests/ml/pytorch/test_pytorch_model_config_pytest.py
tests/ml/pytorch/test_pytorch_model_upload_pytest.py

The main branch does not run CI against any 8.x clusters so there is reason to check the 8.x version.

Remove redundant version checks in tests

---

eland/cli/eland_import_hub_model.py
setup.py

Today, Eland 9.0 works fine on an Elasticsearch 8.15.2 server, but since we're no longer testing for it, should we disable it?

Forbid Elasticsearch 8 client or server

---

CHANGELOG.rst
eland/_version.py

Closes https://github.com/elastic/eland/pull/788. I'm opening a new pull request because our release tooling does some preprocessing magic before opening the pull request.

Release 9.0.1

---

CHANGELOG.rst
eland/_version.py

Closes https://github.com/elastic/eland/pull/789. I'm opening a new pull request because our release tooling does some preprocessing magic before opening the pull request.

Release 8.18.2

---

setup.py
tests/ml/pytorch/test_pytorch_model_upload_pytest.py

Sentence Transformers v5 adds support for sparse embedding models. v5 is now necessary for importing sparse models such as https://huggingface.co/naver/splade-v3-distilbert, without the upgrade the import fails with a `ModuleNotFoundError`
```
docker pull docker.elastic.co/eland/eland:9.0.1
docker run -it --rm --network host docker.elastic.co/eland/eland:9.0.1 \
eland_import_hub_model \
--url 'http://host.docker.internal:9200/' \
-u elastic-admin -p elastic-password \
--hub-model-id 'naver/splade-v3-distilbert' \
--task-type text_expansion --insecure
ModuleNotFoundError: No module named 'sentence_transformers.sparse_encoder'
```
A test has been added to cover this failure. 
The previous requirements for Sentence Transformers was `>=2.1.0,<=2.7.0` making the change to v5 a big leap but …

Upgrade Sentence Transformers and Transformers 
