- CONTRIBUTING.md
- docs/requirements-docs.txt
- docs/source/conf.py
- Update the github documentation repository
- Change the documentation theme
- Add pandoc requirement to the contribution
- Fix minor issue with the installation of pandas instructions
Closes #157
Closes #158
> Fix documentation related issues

- CHANGELOG.rst
- eland/_version.py
- setup.py
We've done quite a bit since last release. :)
Big thank you to @mesejo for contributing so many new changes :rocket:
> Prepare release 7.6.0a5

- eland/operations.py
- eland/query.py
- eland/tasks.py
> Make QueryParams a dataclass

- docs/requirements-docs.txt
Lost these on accident in #200
> Restore documentation requirements

- README.md
- docs/source/conf.py
- docs/source/index.rst
> Add Conda Forge installation instructions

- eland/ml/imported_ml_model.py
- eland/ml/transformers/lightgbm.py
- eland/ml/transformers/xgboost.py
- eland/tests/ml/test_imported_ml_model_pytest.py
Adds testing coverage and fixes some latent bugs in model transformers.
> [ML] testing supported objectives and boosters

- eland/ml/transformers/xgboost.py
- eland/tests/ml/test_imported_ml_model_pytest.py
> Fix get_feature_id() for named feature 0

- .github/workflows/ci.yml
- docs/source/reference/dataframe.rst
Also waiting for the RTD commit status so I can require it on PRs :)
> Add linting GitHub Actions, fix docs

- docs/sphinx/reference/api/eland.DataFrame.es_match.rst
- docs/sphinx/reference/api/eland.Series.es_match.rst
- docs/sphinx/reference/dataframe.rst
- docs/sphinx/reference/series.rst
- eland/dataframe.py
- eland/operations.py
- eland/query_compiler.py
- eland/series.py
- eland/tests/dataframe/test_es_match_pytest.py
- eland/tests/query_compiler/test_es_match_pytest.py
- eland/tests/series/test_es_match.py
> Add support for es_match() to DataFrame and Series

- eland/field_mappings.py
- eland/operations.py
- eland/tests/dataframe/test_utils_pytest.py
- eland/tests/etl/test_pandas_to_eland.py
> Allow passing dictionaries for es_type_overrides

- CHANGELOG.rst
- eland/_version.py
- setup.py
Big release here!
- Highlights are initial support for `groupby()` and lots of work to `pandas_to_eland()`.
- Marking the package as beta through the version (`b1`)
- Thanks to community contributor @V1NAY8 who contributed a ton of features in this release :tada: :bowing_man:
> Release 7.10.0b1

- .gitignore
- noxfile.py
- requirements-dev.txt
Closes #314 
Added pytest-coverage
@sethmlarson  Please Review it :)
> Add pytest-coverage

- README.md
- docs/guide/dataframes.asciidoc
- docs/guide/index.asciidoc
- docs/guide/machine-learning.asciidoc
- docs/guide/overview.asciidoc
- docs/sphinx/reference/dataframe.rst
> Add more sections for elastic.co/guide

- .ci/jobs/defaults.yml
- .ci/run-repository.sh
- .ci/run-tests
- .ci/test-matrix.yml
- noxfile.py
> Jenkins matrix improvement to support Pandas 1.2.0 and 1.3.0

- eland/actions.py
- eland/common.py
- eland/dataframe.py
- eland/operations.py
- eland/query_compiler.py
- tests/notebook/test_demo_notebook.ipynb
Closes #368 
@sethmlarson Take a look
> Switch to Point-in-Time with search_after instead of using scroll APIs

- eland/plotting/_matplotlib/hist.py
- noxfile.py
- setup.cfg
Related to #327 
This PR bumps test coverage from 89% to 90%
Referenced: https://github.com/pytest-dev/pytest-cov/issues/428#issuecomment-821063750
@sethmlarson  Take a 👀
> Add excluded lines for coverage and improve coverage

- eland/dataframe.py
> Fix some document formats

- tests/dataframe/test_drop_pytest.py
- tests/dataframe/test_es_match_pytest.py
- tests/dataframe/test_repr_pytest.py
- tests/dataframe/test_sample_pytest.py
For #327 
This PR will increase the coverage by reducing the misses from 309 to 295. 
@sethmlarson Take a look :)
> Improve coverage for dataframe.py

- eland/dataframe.py
This PR optimizes `df.info` where `self.columns` and its `len()` is called like so many times, which always calculates and fetches it back. 
So, call it once, re use it
Also converted `_get_columns` directly to `columns` method with property.
@sethmlarson  take a look :)
> Refactor `df.info()` for better readability

- requirements-dev.txt
- setup.py
In preparation for an 8.0 release, this updates PyTorch NLP dependencies
to more recent and latest minor versions. Amongst other things, this
introduces a fix from transformers that is helpful for text embedding
tasks with certain DPR models.
See: https://github.com/huggingface/transformers/issues/13670
> Upgrade PyTorch dependencies to latest

- CHANGELOG.rst
- eland/_version.py
First pre-release of the 8.x release stream.
> Release 8.0.0-beta1

- eland/ml/pytorch/transformers.py
- tests/ml/pytorch/test_pytorch_model_pytest.py
This adds the capability to upload a MPNet type model to Elasticsearch. 
Relates to https://github.com/elastic/elasticsearch/pull/82234
> [ML] adding MPNet model support for pytorch

- CHANGELOG.rst
- eland/_version.py
- requirements-dev.txt
- setup.py
Closes https://github.com/elastic/eland/issues/382
> Release 8.0.0

- eland/ml/pytorch/_pytorch_model.py
- eland/ml/pytorch/transformers.py
Related to: https://github.com/elastic/elasticsearch/pull/84777
This allows BART and RoBERTa models to be uploaded to Elasticsearch for our currently defined NLP tasks.
> [ML] add roberta bart transformer upload support

- README.md
- bin/eland_import_hub_model
- eland/ml/pytorch/_pytorch_model.py
- eland/ml/pytorch/nlp_ml_model.py
- eland/ml/pytorch/transformers.py
- tests/ml/pytorch/test_pytorch_model_pytest.py
This adds some more definite types for our NLP tasks and tokenization configurations.
This is the first step in allowing users to more easily import their own transformer models via something other than hugging face.
> [ML] Improve NLP model import by using nicely defined types

- docs/guide/machine-learning.asciidoc
Relates to https://github.com/elastic/eland/pull/462, https://github.com/elastic/eland/pull/461
This PR copies content into the [eland documentation](https://www.elastic.co/guide/en/elasticsearch/client/eland/current/machine-learning.html) which was originally added to the ML guide in
https://github.com/elastic/stack-docs/pull/2132
https://eland_466.docs-preview.app.elstc.co/guide/en/elasticsearch/client/eland/master/machine-learning.html
> Add authentication methods for import model script

- eland/ml/pytorch/traceable_model.py
Quantization has not actually been applied on the model.
This commit addresses that.
> [ML] ensure quantization is applied

- docs/guide/machine-learning.asciidoc
closes https://github.com/elastic/eland/issues/476
> Update python example

- CHANGELOG.rst
- eland/_version.py
Will be tagged and released on Monday.
> Release v8.3.0

- docs/guide/machine-learning.asciidoc
Minor format fix for the eland ML docs.
> Minor format fix

- eland/field_mappings.py
- tests/field_mappings/test_compat_field_caps_pytest.py
Closes https://github.com/elastic/eland/issues/523
> Add a compatibility layer for Elasticsearch server 8.5.0 field_caps API

- bin/eland_import_hub_model
- noxfile.py
Relates https://github.com/elastic/eland/pull/552
**Issue**:
```console
C:\Users\YouheiSakurai\git\myeland>python -m black --version
python -m black, 23.3.0 (compiled: yes)
Python (CPython) 3.11.0
C:\Users\YouheiSakurai\git\myeland>python -m black --check --target-version=py38 bin\eland_import_hub_model
would reformat bin\eland_import_hub_model
Oh no! 💥 💔 💥
1 file would be reformatted.
```
**Solution**:
```
C:\Users\YouheiSakurai\git\myeland>python -m black --target-version=py38 bin\eland_import_hub_model
reformatted bin\eland_import_hub_model
All done! ✨ 🍰 ✨
1 file reformatted.
```
> Apply black to comply with the code style

- .buildkite/pull-requests.json
The slug did not match the Buildkite pipeline.
> Fix Buildkite builds on pull requests

- setup.py
Closes https://github.com/elastic/eland/issues/609
> Bump transformers to fix private model support

- docs/sphinx/development/contributing.rst
There were some backticks that were not required in the docs. This removes them :-)
> Small cosmetic fix to the docs

- eland/dataframe.py
- eland/field_mappings.py
- eland/ml/exporters/_sklearn_deserializers.py
- eland/ml/pytorch/traceable_model.py
- eland/ml/pytorch/transformers.py
- eland/ml/transformers/lightgbm.py
- eland/operations.py
- noxfile.py
- tests/dataframe/test_iterrows_itertuples_pytest.py
This is currently blocking https://github.com/elastic/eland/pull/656.
> Switch to 2024 black style

- tests/ml/test_ml_model_pytest.py
> Mute the Learning to Rank tests

- README.md
- docs/guide/machine-learning.asciidoc
Changing the Pytorch version recommendation for consistency with other docs and ensuring this keeps working with new version releases.
> Update machine-learning.asciidoc - pytorch version dependency

- docs/guide/machine-learning.asciidoc
> Document TLS/SSL options for import script

- docs/guide/machine-learning.asciidoc
This PR updates the list of available task types in the `NLP with PyTorch` section.
> [DOCS] Completes the list of available NLP task types

- README.md
> Revert "Add feedback request to README"

- noxfile.py
* Switch to black's 2025 code style (#749)
(cherry picked from commit aa5196e)
* Run nox -rs format
---------
Co-authored-by: Quentin Pradet <quentin.pradet@elastic.co>
> [Backport 8.x] Switch to black's 2025 code style (#756)

- CHANGELOG.rst
- eland/_version.py
Relates https://github.com/elastic/eland/pull/774
> Release 8.18.1
